### ISSUE TITLE
Because it stopped working or pairing code?

### ISSUE THREAD

**Issue by maickom88** [EvolutionAPI/evolution-api#1471]
### Welcome!

- [x] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

From nothing, the pairing code stopped working, it doesn't work anymore like before. As you still generate the code when including it on WhatsApp, it gives it as an invalid code.

### What did you expect?

Correct the code to pair

### What did you observe instead of what you expected?

Correct the code to pair

### Which version of the API are you using?

2.2.3

### What is your environment?

Windows

**Comment by henrique-nhrl** [comment]
Realmente parou de funcionar. Tenho varias instalaçẽos e todas pararam.

**Comment by brunaagathaph1** [comment]
Minha aplicação é mobile e uso somente o codgo pra se conectar. Agora pagou tudo.

**Comment by VitorS0uza** [comment]
tambem mesmo problema. pairing code nao funciona

**Comment by JonathanLopesM** [comment]
Aqui também parou, estou atrás de uma versão que siga funcionando. testei até a v2.2.1, não lembro qual versão estava pois estava :latest no compose. se alguém puder ajudar...

**Comment by cendyandreoli** [comment]
Alguma atualização sobre o problema? Foi alguma atualização de política do WhatsApp? Tem algum fix mapeado? Alguém conseguiu contornar em outra versão?

**Comment by cendyandreoli** [comment]
Any updates on the issue? Was it due to a WhatsApp policy change? Is there any fix mapped out? Has anyone managed to work around it in another version?

**Comment by cendyandreoli** [comment]
this issue are fixed on Baileys https://github.com/WhiskeySockets/Baileys/issues/1448

**Comment by NieriDantas** [comment]
> esse problema foi corrigido no Baileys [WhiskeySockets/Baileys#1448](https://github.com/WhiskeySockets/Baileys/issues/1448)

tudo bem? nao entendi o post que mencionou, como resolver esse problema ? alterando algum campo na stack
?

**Comment by NieriDantas** [comment]
Alguem conseguiu entender o motivo ? conseguiram resolver?

**Comment by dpaes** [comment]
if what @cendyandreoli says its working on 6.7.17 of baileys, in the newest version of evolution api will work paircode fine. try to use develop version or docker hub evoapicloud/evolution-api:homolog (its 2.3.0 in development)

**Comment by RenanAmaro** [comment]
I'm facing the same issue. I'm using version 2.3.3, but it still doesn't work. The code is generated, but I get an error when trying to use it in WhatsApp. Has anyone found an alternative solution?

**Comment by dpaes** [comment]
@RenanAmaro cant be 2.3.3 version, the last deploy version its 2.2.3, and the develop version its 2.3.0

**Comment by JonathanLopesM** [comment]
> if what [@cendyandreoli](https://github.com/cendyandreoli) says its working on 6.7.17 of baileys, in the newest version of evolution api will work paircode fine. try to use develop version or docker hub evoapicloud/evolution-api:homolog (its 2.3.0 in development). [@maickom88](https://github.com/maickom88) [@henrique-nhrl](https://github.com/henrique-nhrl) [@brunaagathaph1](https://github.com/brunaagathaph1) [@JuniorrMacedo](https://github.com/JuniorrMacedo) [@VitorS0uza](https://github.com/VitorS0uza) [@JonathanLopesM](https://github.com/JonathanLopesM) [@cendyandreoli](https://github.com/cendyandreoli) [@NieriDantas](https://github.com/NieriDantas)

I'll test it next, if it works I'll let you know

**Comment by afcasasfranco** [comment]
Same her on Docker, not show QR codes

**Comment by luimatheo99** [comment]
I tested it in version 2.2.3 and in the homologated version, but the pairingCode is still not connecting.

**Comment by JahirSantos** [comment]
Muchachos ya se solucono solo cambien la CONFIG_SESSION_PHONE_VERSION en su venv no importa la version que tengan cambienla por : CONFIG_SESSION_PHONE_VERSION=2.3000.1023204200 y reinicien su servicio y funcionara nuevamente

**Comment by afcasasfranco** [comment]
> Cambie de la version 2.2.3 a la version 2.3.0 y aun asi no se genera QR y a su vez no hace paringCode

Pude solucionar colocando en el .env lo siguiente, eso si borre memoria redis Postgres y archivos de persistencia de Docker.

CONFIG_SESSION_PHONE_VERSION=2.3000.1023204200root@homelab:

**Comment by pedrormc** [comment]
mine is not showing any qr code, but also when I try to send a message it shows me this error: 

"message": 
"500 - "{\"status\":500,\"error\":\"Internal Server Error\",\"response\":{\"message\":[\"Error: Timed Out\"]}}"",
"name": 
"AxiosError",
"stack": 
"AxiosError: Request failed with status code 500\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/axios@1.8.3/node_modules/axios/lib/core/settle.js:19:12)\n    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/axios@1.8.3/node_modules/axios/lib/adapters/http.js:547:9)\n    at RedirectableRequest.emit (node:events:536:35)\n    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:398:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)\n    at Object.onceWrapper (node:events:639:26)\n    at ClientRequest.emit (node:events:524:28)\n    at HTTPParser.parserOnIncomingClient (node:_http_client:702:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)\n    at Socket.socketOnData (node:_http_client:544:22)\n    at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/axios@1.8.3/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at invokeAxios (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:206:10)\n    at proxyRequestToAxios (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:656:20)\n    at Object.request (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:1698:4)",
"code": 
"ERR_BAD_RESPONSE",
"status": 
500

**Comment by cendyandreoli** [comment]
[SOLUTION] Guys, I create a new image with the stable version of Baileys and It's working https://hub.docker.com/r/cendyandreoli/evolution-api

**Comment by McNickSisto** [comment]
`CONFIG_SESSION_PHONE_VERSÃO=2.3000.1023204200
`
This solved the QR code not being generated. However, when scanning it I get a WhatsApp error : "cannot link new devices at this time". I tried with both professional and personal WhatsApp.

Then, when I tried generating the code, it does not work. Any news / thoughts ?

**Comment by NieriDantas** [comment]
> [SOLUÇÃO] Pessoal, criei uma nova imagem com a versão estável do Baileys e está funcionando https://hub.docker.com/r/cendyandreoli/evolution-api

ola amigo! isso resolveu o problema de codigo de pareamento?

**Comment by agenciageraleads** [comment]
por aqui nada também usando a versao 2.2.3, gera o codigo mas nunca dá certo de conectar.

**Comment by JonathanLopesM** [comment]
> [SOLUTION] Guys, I create a new image with the stable version of Baileys and It's working https://hub.docker.com/r/cendyandreoli/evolution-api

Cool, what did you need to change? Did you just change the Baileys package?
